=== windowshastalavista/codw/xml/equipaggiamenti.dtd
<!ELEMENT equipaggiamenti (equipaggiamento+)> 
<!ELEMENT equipaggiamento (nome?, descrizione?)> 
<!ELEMENT nome (#PCDATA)> 
<!ELEMENT descrizione (#PCDATA)> 

<!ATTLIST equipaggiamento tipo CDATA #REQUIRED>

=== windowshastalavista/codw/xml/equipaggiamenti.xml
<!DOCTYPE equipaggiamenti SYSTEM "equipaggiamenti.dtd">
<?xml-stylesheet type="text/xsl" version="1.0" href="./equipaggiamenti.xsl"?>
<equipaggiamenti>
  <equipaggiamento tipo="Granate e Armi da lancio">
    <nome>Molotov</nome>
    <descrizione> Ordigno incendiario. </descrizione>
  </equipaggiamento>

  <equipaggiamento tipo="Granate e Armi da lancio">
    <nome>Granata</nome>
    <descrizione> Arma da lancio deflagrante. </descrizione>
  </equipaggiamento>

  <equipaggiamento tipo="Granate e Armi da lancio">
    <nome>Granata_a_grappolo</nome>
    <descrizione> Granata che una volta detonata si separa in diverse granate più piccole. </descrizione>
  </equipaggiamento>

  <equipaggiamento tipo="Granate e Armi da lancio">
    <nome>Granata_Stordente</nome>
    <descrizione> Granata che all'impatto causa difficoltà uditive e visive. </descrizione>
  </equipaggiamento>

  <equipaggiamento tipo="Granate e Armi da lancio">
    <nome>Tomahawk</nome>
    <descrizione> Ascia da lancio. </descrizione>
  </equipaggiamento>

  <equipaggiamento tipo="Granate e Armi da lancio">
    <nome>9-Bang</nome>
    <descrizione> Granata che una volta detonata crea un flash provocando difficoltà visive. </descrizione>
  </equipaggiamento>

   <equipaggiamento tipo="Granate e Armi da lancio">
    <nome>Granata_fumogena</nome>
    <descrizione> Una volta detonata crea una cortina di fumo. </descrizione>
  </equipaggiamento>

  <equipaggiamento tipo="Equipaggiamenti armi">
   <nome>Impugnatura</nome>
   <descrizione> Riduce il rinculo. </descrizione>
 </equipaggiamento>

 <equipaggiamento tipo="Equipaggiamenti armi">
  <nome>Calcio</nome>
  <descrizione> Aumenta la mobilità dell'arma. </descrizione>
</equipaggiamento>

<equipaggiamento tipo="Equipaggiamenti armi">
 <nome>Caricatore_rapido</nome>
 <descrizione> Aumenta la velocità di ricarica. </descrizione>
</equipaggiamento>

<equipaggiamento tipo="Equipaggiamenti armi">
 <nome>Caricatore_esteso</nome>
 <descrizione> Aumenta la capienza del caricatore. </descrizione>
</equipaggiamento>

<equipaggiamento tipo="Equipaggiamenti armi">
 <nome>Canna_lunga</nome>
 <descrizione> Aumenta la gittata del proiettile. </descrizione>
</equipaggiamento>

<equipaggiamento tipo="Equipaggiamenti armi">
 <nome>Silenziatore</nome>
 <descrizione> Riduce il suono emesso durante lo sparo. </descrizione>
</equipaggiamento>

<equipaggiamento tipo="Equipaggiamenti speciali">
  <nome>Mina_a_maglia</nome>
  <descrizione> Mina che si innesca una volta passati sulla linea del raggio laser. </descrizione>
</equipaggiamento>

<equipaggiamento tipo="Equipaggiamenti speciali">
  <nome>Barricata</nome>
  <descrizione> Barricata portatile che una volta poggiata a terra si apre, creando una copertura dai nemici. </descrizione>
</equipaggiamento>

<equipaggiamento tipo="Equipaggiamenti speciali">
  <nome>Filo_spinato</nome>
  <descrizione> Filo di ferro dentato che impedisce ai nemici di oltrepassare senza recarsi danno. </descrizione>
</equipaggiamento>

<equipaggiamento tipo="Equipaggiamenti speciali">
  <nome>Rampino</nome>
  <descrizione> Pistola-rampino permette di aggangianrsi a qualsiasi oggetto, ideale per salire sui tetti in maniera rapidà. </descrizione>
</equipaggiamento>

<equipaggiamento tipo="Equipaggiamenti speciali">
  <nome>Dardo_sensore</nome>
  <descrizione> Dardo che attraverso sensori di calore individua i nemici vicini. </descrizione>
</equipaggiamento>

<equipaggiamento tipo="Armature e kit medici">
  <nome>Armatura_lv1</nome>
  <descrizione>Armatura comune, buona per le fasi iniziale della partita. </descrizione>
</equipaggiamento>

<equipaggiamento tipo="Armature e kit medici">
  <nome>Armatura_lv2</nome>
  <descrizione>Armatura rara, buona per tutta la durata della partita. </descrizione>
</equipaggiamento>

<equipaggiamento tipo="Armature e kit medici">
  <nome>Armatura_lv3</nome>
  <descrizione>Armatura ultra-rara, ottima per tutta la durata della partita. </descrizione>
</equipaggiamento>

<equipaggiamento tipo="Armature e kit medici">
  <nome>Benda</nome>
  <descrizione>Breve tempo di applicazione, permette di recuperare 25 punti vita. </descrizione>
</equipaggiamento>

<equipaggiamento tipo="Armature e kit medici">
  <nome>Kit_medico</nome>
  <descrizione>Kit con discreto tempo di applicazione, permette di recuperare 50 punti vita.</descrizione>
</equipaggiamento>

<equipaggiamento tipo="Armature e kit medici">
  <nome>Kit_anti-trauma</nome>
  <descrizione>Kit con elevato tempo di applicazione, permette di recuperare pienamente la salute. </descrizione>
</equipaggiamento>
</equipaggiamenti>
